### ISSUE TITLE
use -rpath-link for libstdc++ ?

### ISSUE THREAD

**Issue by Crghilardi** [JuliaGeo/GDAL.jl#105]
cross posting here just as an FYI in case it helps anything.

I recently submitted `libgeotiff` to Yggdrasil, and in my initial attempt I used `export LDFLAGS="$LDFLAGS -lstdc++` to fix some linking issues. In the review, it sounds like that is [not the recommended pattern](https://github.com/JuliaPackaging/Yggdrasil/pull/2195#issuecomment-736016231) and using the [-rpath-link flag](https://github.com/JuliaPackaging/Yggdrasil/blob/e122c7e55a3a69ef83a945e6997c63113f8b8f34/L/libgeotiff/build_tarballs.jl#L23) is preferred? 

I don't know how this interacts with all the patches needed to make PROJ and GEOS behave correctly. Will try to tinker with it a little bit and see if anything weird happens.

**Comment by visr** [comment]
Yeah, would probably be good to make that change. I don't think it should have any impact, so it should be relatively safe.

**Comment by Crghilardi** [comment]
completed in [Yggdrasil PR 2334](https://github.com/JuliaPackaging/Yggdrasil/pull/2334)
