### ISSUE TITLE
Test all downstream packages automatically

### ISSUE THREAD

**Issue by evetion** [JuliaGeo/GDAL.jl#144]
Given the recent discussion and breakage in https://github.com/yeesian/ArchGDAL.jl/pull/354.

Even with no breaking changes in GDAL.jl itself, new GDAL_jll versions can sometimes break downstream APIs.

**Comment by yeesian** [comment]
I guess it's a case of https://www.hyrumslaw.com/ haha

**Comment by visr** [comment]
Would be good to have this. Fixing https://github.com/yeesian/ArchGDAL.jl/issues/158 could help reduce noise as well. So as mentioned in the other issue let's use these downstream tests also to judge whether new GDAL_jll versions need to be released as breaking GDAL.jl releases. The current GDAL.jl 1.5 should really have been GDAL.jl 2.0 if we want to take semver seriously.
