### ISSUE TITLE
Feature suggestion: list of supported drivers

### ISSUE THREAD

**Issue by tpoisot** [JuliaGeo/GDAL.jl#148]
Hi! @gottacatchenall and I were looking for a list of drivers supported by GDAL.jl, and it *seems* like the only one is part of the test suite ([e.g. here](https://github.com/JuliaGeo/GDAL.jl/blob/040bda4ac1b57fbd18239036f08c8b8fcf06849e/test/drivers.jl)).

Would it make sense to stick this array in a variable, that doesn't need to be exported? It would allow other packages to perform checks like `driver in GDAL.supported_drivers`, for example.

If that makes sense (and after reading #65 I know the set of supported drivers might change), I would be happy to open a PR.

**Comment by gottacatchenall** [comment]
agreed! and similarly i think a list of supported EPSG codes and methods for transforming between them could benefit GDAL/ArchGDAL.jl

**Comment by yeesian** [comment]
I haven't translated them into the corresponding code of GDAL.jl, but you can get them via [`ArchGDAL.listdrivers(...)`](https://github.com/yeesian/ArchGDAL.jl/blob/0de86cc09e967163f550c30ddc11a0be3ce846fb/src/driver.jl#L70). It should be better documented, but just thought I'd let you know in advance of any improvements we can make.

**Comment by tpoisot** [comment]
Thanks @yeesian, that's perfect for what we need!

**Comment by visr** [comment]
It's worth noting that for the `driver in GDAL.supported_drivers` usecase you mentioned, a more direct approach would be to use [`gdalgetdriverbyname`](https://gdal.org/doxygen/gdal_8h.html#ae8ae868eef1e4773283d137b0a1adfc4) / `ArchGDAL.getdriver`. If a C_NULL is returned, it is not available.

For listing all drivers, you can loop from over all the drivers by index based on `gdalgetdrivercount` and `gdalgetdriver`, which is what ArchGDAL probably does.

**Comment by yeesian** [comment]
I think the request for EPSG codes is still a valid one; I looked it up and the best I found so far is https://gis.stackexchange.com/questions/300846/get-a-list-of-all-supported-epsg-code-from-ogr -- it will be nice to have a way of making it more accessible. Opened up an issue in https://github.com/yeesian/ArchGDAL.jl/issues/370.

**Comment by evetion** [comment]
> agreed! and similarly i think a shared `const` of supported EPSG codes (e.g. to pass to  `gdalwarp`)  could benefit GDAL/ArchGDAL.jl 

@gottacatchenall How would that be useful to you? Do you just want to check the validity of your transform?

**Comment by gottacatchenall** [comment]
> @gottacatchenall How would that be useful to you? Do you want to check the validity of your transform?

Yes, for both checking the validity of a transform, and potentially for imposing conditions on what are valid EPSGs to run a model with given the bounding box of the data, e.g. EPSG 32198 is specific to Quebec but can be applied to raster data from anywhere with `gdalwarp`, so we would like to throwing a warning for inputs that are far from the region a specific transformation is meant for

**Comment by evetion** [comment]
> Yes, for both checking the validity of a transform, and potentially for imposing conditions on what are valid EPSGs to run a model with given the bounding box of the data, e.g. EPSG 32198 is specific to Quebec but can be applied to raster data from anywhere with `gdalwarp`, so we would like to throwing a warning for inputs that are far from the region a specific transformation is meant for 

Ah, that makes sense. Might be good to update the issue, because now it reads like we just want a (very long) list of epsg numbers. We actually want a validity and conform bounds checks.
