### ISSUE TITLE
Julia nightly and libcurl 8

### ISSUE THREAD

**Issue by joa-quim** [JuliaGeo/GDAL.jl#152]
Hi,

``libcurl 8`` is raising quite some issues and after some troubles we think we got them solved in GMT and Julia nightly, but installation still fails now because of a GDAL_jll version restriction.

![image](https://user-images.githubusercontent.com/537321/232327672-1c95128b-7328-416e-b2e8-e5bd2f35f1cf.png)

If interested, this is the issue https://github.com/JuliaLang/julia/issues/49361 describing the steps takes to fix on the GMT.jl side (that also depends on libCURL_jll). I am, however, a bit puzzled because on Windows and Julia nightly I could just ``] add GDAL`` with no problems. Have you tried GDAL_jll on Julia nightly?

**Comment by visr** [comment]
I triggered CI for nightly recently in #150, and that shows that indeed GDAL_jll is currently broken on nightly. If allowing libcurl 8 compat is enough to fix that, it would be great to add that in Yggdrasil.

If we also want to tackle https://github.com/JuliaGeo/GDAL.jl/issues/151#issuecomment-1507086968 we might need to first rebuild libtiff.

**Comment by joa-quim** [comment]
Expanding the compat range in Yggrasil and the [registry ](https://github.com/JuliaRegistries/General/blob/master/jll/G/GMT_jll/Compat.toml) did solve the issue for GMT.

Regarding the libtiff issue, why are you not using the one that comes internally with GDAL? It would save from issues like this, no?

**Comment by visr** [comment]
I'm not sure why that would avoid any issues. The external lib was available and is also used for PROJ_jll, so using it avoids unneccesary duplication.

**Comment by joa-quim** [comment]
Yes, right PROJ needs it too.

**Comment by visr** [comment]
Fixed in https://github.com/JuliaRegistries/General/pull/88557.

@joa-quim next time you fix the compat in the registry feel free to also change it for other packages that are affected besides GMT. I just found your PR https://github.com/JuliaRegistries/General/pull/81657 yesterday because it wasn't linking to any of the relevant issues.
