### ISSUE TITLE
Update to GDAL_jll 301.800.300+0  ?

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaGeo/GDAL.jl#167]
The NetCDF_jll v400.902.208 is compatible with  GDAL_jll 301.800.300 but not with 301.700.
Would it possible to update GDAL_jll to version 301.800.300, so that I can use NetCDF_jll v400.902.208 and GDAL in the same environment? 

NetCDF_jll v400.902.208 fixed a bug for accessing opendap server:
https://github.com/Alexander-Barth/NCDatasets.jl/issues/244

**Comment by visr** [comment]
The major version of those is the same, v301, so we are already compatible with GDAL 3.8 right?

```
Project GDAL v1.7.1
Status `C:\Users\visser_mn\.julia\dev\GDAL\Project.toml`
  [fa961155] CEnum v0.5.0
  [a7073274] GDAL_jll v301.800.300+0
  [58948b4f] PROJ_jll v901.300.0+0
  [ca575930] NetworkOptions v1.2.0
```

**Comment by Alexander-Barth** [comment]
You are right :-) 
In my case the problem was with gdk_pixbuf_jll (dependency of ProfileView) which prevented to upgrade of [Libtiff_jll](https://github.com/JuliaBinaryWrappers/gdk_pixbuf_jll.jl/blob/2604f9c33272449f3f7cff7a666b735fb771452c/Project.toml) to version 4.5.1 and the installation of GDAL 1.7.

Sorry for the noise and have a nice week-end  :-)

**Comment by visr** [comment]
Ah yes, this version conflict should be resolved with a rebuild of `gdk_pixbuf`, I submitted https://github.com/JuliaPackaging/Yggdrasil/pull/7996 but it still has some issues.

**Comment by visr** [comment]
This is fixed now with the new `gdk_pixbuf` release.
