### ISSUE TITLE
Build Arrow_jll with Snappy 1.2 compat

### ISSUE THREAD

**Issue by kongdd** [JuliaGeo/GDAL.jl#171]
- Julia: 1.10.2
- GDAL.jl: 1.7.1

A fresh env, with only one package GDAL.jl. GDAL.jl was failed to build.
```julia
(v1.10) pkg> st
Status `D:\.julia\environments\v1.10\Project.toml`
  [add2ef01] GDAL v1.7.1
```

```julia
julia> using GDAL
Precompiling GDAL
        Info Given GDAL was explicitly requested, output will be shown live
ERROR: LoadError: InitError: could not load library "d:\.julia\artifacts\dcd0721a2a49cfb8916395419701035173b57955\bin\libarrow.dll"
The specified procedure could not be found.
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl .\libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl .\libdl.jl:116
  [3] macro expansion
    @ d:\.julia\packages\JLLWrappers\pG9bm\src\products\library_generators.jl:63 [inlined]
  [4] __init__()
    @ Arrow_jll d:\.julia\packages\Arrow_jll\s7Yjm\src\wrappers\x86_64-w64-mingw32-cxx11.jl:17
```

**Comment by kongdd** [comment]
This issue may originate from the update of `https://github.com/JuliaBinaryWrappers/snappy_jll.jl`

**Comment by visr** [comment]
I submitted https://github.com/JuliaRegistries/General/pull/105696 to add this compat in the registry. That should fix the breakage. Besides that someone should try to build a new Arrow_jll of the latest version, 16. And probably add snappy_jll compat to the minor version 1.2.

**Comment by kongdd** [comment]
Thank you.

**Comment by visr** [comment]
Registry PR is merged, I renamed this issue as a reminder to rebuild Arrow_jll.

**Comment by visr** [comment]
Fixed in https://github.com/JuliaPackaging/Yggdrasil/pull/10017
