### ISSUE TITLE
Is GDAL_jll broken on Windows?

### ISSUE THREAD

**Issue by joa-quim** [JuliaGeo/GDAL.jl#173]
Hi,

I updated GMT_jll that depends on GDAL_jl and now on Windows the CI build fails with
```
Failed to precompile GDAL_jll [a7073274-a066-55f0-b90d-d619367d196c] to "C:\\Users\\runneradmin\\.julia\\compiled\\v1.10\\GDAL_jll\\jl_422D.tmp".
ERROR: LoadError: InitError: could not load library "C:\Users\runneradmin\.julia\artifacts\356b5bdc540243e0fadea8d16f948dc26c1f6eeb\bin\libgeotiff.dll"
The specified module could not be found. 
```

https://github.com/GenericMappingTools/GMT.jl/actions/runs/9236132479/job/25411639570?pr=1451#step:12:277

**Comment by visr** [comment]
Yeah it is, see also https://github.com/yeesian/ArchGDAL.jl/issues/427 and its linked discussion.

**Comment by joa-quim** [comment]
Ok, thanks. But I'm afraid the proposed patch won't work for me because I inadvertently set compats in GMT_jll to
```
PROJ_jll = "901.300.0"
GDAL_jll = "301.900"
```

**Comment by joa-quim** [comment]
I still find the compats setting quite confusing. Do you think the best for now would be to trigger another `GMT_jll` build with the compat set to `301.800.500`? And how to set it such that when a new build of `GDAL_jll` arrives I do not need to rebuild `GMT_jll`?
GDAL3.9 has a nice new `geodeticarea` function that I would like to use.

**Comment by visr** [comment]
Actually the `GDAL_jll@301.900` (i.e. not 901) works fine for me, also on CI apart from some minor test changes, see #172.

https://github.com/JuliaBinaryWrappers/GDAL_jll.jl/releases

The 901 build adds more GDAL dependencies and enables more features, both for GDAL 3.9:

```
(proj94) pkg> add GDAL_jll@301.900
   Resolving package versions...
    Updating `D:\temp\proj94\Project.toml`
⌃ [a7073274] ↓ GDAL_jll v301.901.0+0 ⇒ v301.900.0+0
    Updating `D:\temp\proj94\Manifest.toml`
⌃ [a7073274] ↓ GDAL_jll v301.901.0+0 ⇒ v301.900.0+0
  [59f7168a] - Giflib_jll v5.2.1+0
  [d4300ac3] - Libgcrypt_jll v1.8.11+0
  [7e76a0d4] - Libglvnd_jll v1.6.0+0
  [7add5ba3] - Libgpg_error_jll v1.49.0+0
  [784f63db] - Qhull_jll v8.0.1003+0
  [aed1982a] - XSLT_jll v1.1.34+0
  [4f6342f7] - Xorg_libX11_jll v1.8.6+0
  [0c0b7dd1] - Xorg_libXau_jll v1.0.11+0
  [a3789734] - Xorg_libXdmcp_jll v1.1.4+0
  [1082639a] - Xorg_libXext_jll v1.3.6+0
  [14d82f49] - Xorg_libpthread_stubs_jll v0.1.1+0
  [c7cfdc94] - Xorg_libxcb_jll v1.15.0+0
  [c5fb5394] - Xorg_xtrans_jll v1.5.0+0
  [c5f90fcd] - libwebp_jll v1.4.0+0
  [efcefdf7] - PCRE2_jll v10.42.0+1
```

**Comment by visr** [comment]
The broken GDAL and PROJ builds have now been merged in the General registry, so I'm closing this. I wrote https://github.com/JuliaPackaging/Yggdrasil/issues/8781 on fixing the build script.
