### ISSUE TITLE
GMT_jll build breaks on Windows because of a "could not load library C:... \libgdal-35.dll"

### ISSUE THREAD

**Issue by joa-quim** [JuliaGeo/GDAL.jl#174]
Both Julia 1.10 & 1.11 CI tests fail on Windows

https://github.com/GenericMappingTools/GMT.jl/actions/runs/9717542318/job/26823436119?pr=1476#step:12:272

https://github.com/GenericMappingTools/GMT.jl/actions/runs/9717542318/job/26823435433?pr=1476#step:12:277

This happens only on Windows and is a very recent failure. Not sure if I can do anything on my side.

**Comment by joa-quim** [comment]
Probably because

https://github.com/JuliaPackaging/Yggdrasil/pull/8965

**Comment by visr** [comment]
Yeah, see https://github.com/JuliaPackaging/Yggdrasil/issues/8781

**Comment by visr** [comment]
Fixed with GDAL_jll v301.901.101.
