### ISSUE TITLE
TODO for registration

### ISSUE THREAD

**Issue by evetion** [JuliaGeo/GDAL.jl#44]
I would really like for this package to be registered. What do you think that needs to be done for this?

- [x]  Fix builds  #42 
- [ ]  Julia 0.7/1.0?

**Comment by visr** [comment]
I don't think we need to wait for Julia 0.7/1.0 (unless it's there by the time we get to it).
But yes, #42 would need to be fixed. I think we can try fixing it by setting up a GDALBuilder with BinaryBuilder.jl, and have it link to the same zlib as Julia. Working on setting it up for GEOS and PROJ first, such that we can use those as dependencies.

And might be good to go through #13 and #19 as well again before we register.

**Comment by visr** [comment]
Ok I'll go ahead and register now. It is passing tests on 0.6 and 0.7 beta (with deprecation warnings).
How about we make a v0.1.0 release, with v0.1.x being for fixing possible bugs on 0.6. Then we can use master to switch to REQUIRE julia 0.7.
