### ISSUE TITLE
Rasterization is excruciatingly slow in GDAL 2.2.4, please update to GDAL 2.3 or 2.4

### ISSUE THREAD

**Issue by niclasmattsson** [JuliaGeo/GDAL.jl#62]
I need to rasterize global shapefiles at high resolution (0.01 degrees, i.e. a 36000x18000 raster). At this resolution, `gdal_rasterize` runs in about 100 seconds using GDAL 2.3 or 2.4 but takes over an hour on GDAL 2.2.4.

Apparently @visr has already updated GDALbuilder.jl with support for version 2.3, but I can't tell why his pull request to GDAL.jl (#60) won't pass tests. It been a while now, perhaps the underlying issue has resolved itself?

Here are sample runs using [gadm3.6.shp](https://biogeo.ucdavis.edu/data/gadm3.6/gadm36_shp.zip) (a shapefile of global administrative borders, 537 MB download).

```
C:\Users\niclas\Downloads>"C:\Program Files\GDAL\release-1911-x64-gdal-2-4-0-mapserver-7-2-2\bin\gdal\apps\gdal_rasterize" --version
GDAL 2.4.0, released 2018/12/14

C:\Users\niclas\Downloads>timemem-1.0 C:\Program Files\GDAL\release-1911-x64-gdal-2-4-0-mapserver-7-2-2\bin\gdal\apps\gdal_rasterize -a ID_0 -ot Byte -tr 0.01 0.01 -te -180 -90 180 90 -co COMPRESS=LZW C:/Stuff/Datasets/gadm36/gadm36.shp globtest1.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
Exit code      : 0
Elapsed time   : 103.82
Kernel time    : 49.44 (47.6%)
User time      : 54.25 (52.3%)
page fault #   : 47641356
Working set    : 3140816 KB
Paged pool     : 255 KB
Non-paged pool : 35 KB
Page file size : 3176800 KB

C:\Users\niclas\Downloads>C:\Users\niclas\.julia\packages\GDAL\vec6Y\deps\usr\bin\gdal_rasterize --version
GDAL 2.2.4, released 2018/03/19

C:\Users\niclas\Downloads>timemem-1.0 C:\Users\niclas\.julia\packages\GDAL\vec6Y\deps\usr\bin\gdal_rasterize -a ID_0 -ot Byte -tr 0.01 0.01 -te -180 -90 180 90 -co COMPRESS=LZW C:/Stuff/Datasets/gadm36/gadm36.shp globtest2.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
Exit code      : 0
Elapsed time   : 3905.56
Kernel time    : 2206.72 (56.5%)
User time      : 1698.69 (43.5%)
page fault #   : 3045007692
Working set    : 2524976 KB
Paged pool     : 392 KB
Non-paged pool : 31 KB
Page file size : 2554800 KB
```

Also since GDAL 2.4 is out, maybe that version should be targeted instead of 2.3.x.

**Comment by visr** [comment]
Interesting, wasn't aware rasterization speed increased so much. Agree about skipping 2.3.x and going straight for the latest release. I've been trying to get there by first updating dependency builds like PROJ and GEOS. Currently stuck on GEOS with https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/407. If this will take a while it might be worth exploring a new GDAL build with the old but working GEOS build. Although there may be other issues in that case related to mixing two builds from very different BinaryBuilder versions.

**Comment by niclasmattsson** [comment]
Thanks for the explanation, I'll follow that BinaryBuilder issue to keep up to date. Just to be clear, the huge increase in rasterization times only seems to happen at very high resolution. If I change target resolution from 0.01x0.01 degrees to 0.1x0.1 degrees then all versions of GDAL between 2.2 and 2.4 finish in 65-75 seconds on my machine. Unfortunately my application needs the higher resolution ... :(

**Comment by visr** [comment]
Ok I see. Note that if you already have a GDAL 2.4 installation on your computer, you can also point GDAL.jl to it by modifying the deps.jl it creates, as a temporary workaround.

**Comment by niclasmattsson** [comment]
Thanks, that would work too. The workaround I've been using is to run the command line version of GDAL from Julia to write a tiff. I'm requesting the update because I'm planning to release a package later this spring for generating input data for energy models, and I'd rather avoid having my users install GDAL separately.

**Comment by visr** [comment]
This should be fast, now that the latest release uses GDAL 3.
