### ISSUE TITLE
Should ArchGDAL.jl be part of GDAL.jl?

### ISSUE THREAD

**Issue by juliohm** [JuliaGeo/GDAL.jl#76]
Would it make sense to migrate ArchGDAL.jl functionality to GDAL.jl?

cc: @yeesian

**Comment by yeesian** [comment]
The nature of the codebases makes it such that it makes more sense to have them in separate packages. GDAL is based on policies for autogenerating and writing code from Clang, and ArchGDAL is based on adhoc decisions for improving the user experience.

**Comment by visr** [comment]
What do you think the main advantage of having them together is?

Perhaps we can be a bit more upfront about the role of this package. Basically, you probably want to use ArchGDAL.jl unless, you want to build your own GDAL abstraction, are familiar with and want to use the GDAL C API, or want to use a function that is in here but not yet available in ArchGDAL.

**Comment by juliohm** [comment]
Thank you all for your quick replies. I was trying to understand this separation just because ArchGDAL.jl (the defacto standard in Julia nowadays?) is not in JuliaGeo, and because the name with the "Arch" way can sometimes be confused with a more low-level "architecture" interpretation.

Maybe renaming the packages to GDAL.jl -> GDALC.jl and ArchGDAL.jl -> GDAL.jl, and having both in JuliaGeo would help somehow? Just sharing what came to mind when I crossed roads with the packages.

**Comment by yeesian** [comment]
ArchGDAL.jl is my experimental/personal take on possible workflows for working with GDAL. The package name and code ownership and activity/discussions reflects its nature.

I don't wish to speculate on what the defacto standard is, but further discussion of the name and purpose of the GDAL.jl package should happen on the discourse forum instead.
